version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    command: --check-caps false --ISCAgent false
    restart: always
    ports: 
      - 19800:1972
      - 30025:30025
      - 57700:52773
      - 53773
    volumes:
      - ./:/irisrun/repo
